---
sysctl_config:
  net.ipv4.tcp_rfc1337: 1
  net.ipv4.tcp_keepalive_time: 7200
  net.ipv4.tcp_keepalive_intvl: 20
  net.ipv4.tcp_keepalive_probes: 3
  net.ipv4.tcp_max_orphans: 16384
  net.ipv4.tcp_abort_on_overflow: 0
  net.ipv4.tcp_tw_reuse: 1
  net.ipv4.tcp_timestamps: 1
