---
- name: Make SSH-only user for tunneling
  user:
    name: "{{ tunnel_user }}"
    uid: "{{ tunnel_user_uid }}"
    shell: "{{ tunnel_user_shell }}"
    create_home: true
    home: "/home/{{ tunnel_user }}"
    system: no
