---
- hosts: all
  become: true
  roles:
    - { role: common, tags: common }
    - { role: sshd, tags: sshd }
    - { role: reverse_tunnel, tags: reverse_tunnel, when: inventory_hostname == 'external_edge' }
