---
- name: Make SSH-only user for tunneling
  user:
    name: "{{ tunnel_user }}"
    uid: "{{ tunnel_user_uid }}"
    shell: "{{ tunnel_user_shell }}"
    create_home: true
    home: "{{ tunnel_user_home }}"
    system: no

- name: Make .ssh directory
  file:
    path: "{{ tunnel_user_home }}/.ssh"
    state: directory
    mode: 0700
    owner: "{{ tunnel_user }}"
    group: "{{ tunnel_user }}"

- name: Fetch public key from external edge
  delegate_to: "external_edge"
  slurp:
    src: "{{ public_key_path }}"
  register: fetched_key
  run_once: true

- name: Set authorized_keys on tunnel user
  copy:
    content: "{{ fetched_key.content | b64decode }}"
    dest: "{{ tunnel_user_home }}/.ssh/authorized_keys"
    owner: "{{ tunnel_user }}"
    group: "{{ tunnel_user }}"
    mode: 0600
