---
- name: Make limits.conf
  template:
    src: limits.conf.j2
    dest: /etc/security/limits.conf
    backup: true

- name: Override sshd service
  template:
    src: sshd.service.j2
    dest: /etc/systemd/system/sshd.service.d/override.conf
  notify:
    - Restart sshd

- name: Make sshd config
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    backup: true
  notify:
    - Restart sshd
